version: "3.7"
services:
  rethinkdb:
    container_name: "parking-system-rethinkdb"
    image: rethinkdb
    volumes:
      - "./volumes/rethinkdb/:/data"
    ports:
      - 8080:8080
  backend:
    container_name: "parking-system-backend"
    build: ../api
    ports:
      - 8081:3000
    depends_on: 
      - rethinkdb
  frontend:
    container_name: "parking-system-frontend"
    build: ../web
    ports:
      - 8082:80
    depends_on:
      - backend