version: "3.7"
services:
  mongo:
    container_name: parking-mongodb
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - /data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks: 
      - mongodb

  mongo-express:
    container_name: parking-mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks: 
      - mongodb

  nosqlclient:
    container_name: parking-nosqlclient
    image: mongoclient/mongoclient
    restart: unless-stopped
    volumes:
      - /data/db
    ports:
      - 8082:3000
    networks: 
      - mongodb

networks: 
  mongodb:
    external: false